name: scattering-emulators-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.9.7
  - numpy=1.21.2
  - scipy=1.7.1
  - matplotlib=3.5.0
  - matplotlib-inline>=0.1.6
  - h5py=3.6.0
  - notebook=6.4.6
  - ipython=7.29.0
  - nbconvert=6.3.0
  - fastcache=1.1.0
  - pip=21.3.1
  - pip:
      - ruamel.yaml==0.17.9
      - smt==1.1.0
      - numba==0.55.2
